name: upnped
description: A Dart library for discovering and controlling UPnP devices.
version: 1.1.1
repository: https://github.com/huffSamuel/upnped
homepage: https://github.com/huffSamuel/upnped

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  device_info_plus: ^10.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  http: ^1.1.0
  platform: ^3.1.4
  rxdart: ^0.27.7
  sprintf: ^7.0.0
  xml: ^6.5.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^4.0.0
  mockito: ^5.4.2
  test: ^1.25.2
  device_info_plus_platform_interface: ^7.0.0